### ISSUE TITLE
Latest version has a breaking change

### ISSUE THREAD

**Issue by deshruch** [google/cel-policy-templates-go#43]
I have a go progam that uses an older version of cel-policy-templates-go. I am unable to find that version in the repo. 
The program I wrote now fails with the latest version giving me this error:
Any guidance on how I could fix this with the latest version?

go: finding module for package github.com/google/cel-policy-templates-go/policy/runtime
go: finding module for package github.com/google/cel-policy-templates-go/policy/model
go: finding module for package github.com/google/cel-policy-templates-go/policy/compiler
go: finding module for package github.com/google/cel-policy-templates-go/policy/parser
go: finding module for package github.com/google/cel-policy-templates-go/policy/limits
C:\Program Files\Go\src\cel-policy-templates-go\policy\engine.go:22:2: no matching versions for query "latest"
C:\Program Files\Go\src\cel-policy-templates-go\policy\engine.go:23:2: no matching versions for query "latest"
C:\Program Files\Go\src\cel-policy-templates-go\policy\engine.go:24:2: no matching versions for query "latest"
C:\Program Files\Go\src\cel-policy-templates-go\policy\engine.go:25:2: no matching versions for query "latest"
C:\Program Files\Go\src\cel-policy-templates-go\policy\engine.go:26:2: no matching versions for query "latest"

It is a pretty simple program:

```package main

import(
    "cel-policy-templates-go/policy"
    "fmt"
    "log"
    "github.com/google/cel-go/cel"
    "github.com/google/cel-go/checker/decls"
)


var (
	stdDecls = cel.Declarations(
		decls.NewIdent("ResourceLocaleID", decls.String, nil),
		decls.NewIdent("UserLocation", decls.String, nil),
		decls.NewIdent("UserNationality", decls.String, nil),

		)
	)


func main(){
  env, _ := cel.NewEnv(stdDecls)
    enfOpts := []policy.EngineOption{
                     				policy.SourceFile(policy.EvaluatorFile, fmt.Sprintf("evaluator-economic-sanctions.yaml")),
                     				policy.SourceFile(policy.TemplateFile, fmt.Sprintf("template-economic-sanctions.yaml")),
                     				policy.SourceFile(policy.InstanceFile, fmt.Sprintf("instance-economic-sanctions.yaml")),
                     			}

    enforcer, err := policy.NewEngine(env, enfOpts...)
    			if err != nil {
    				log.Fatalf("Error creating an Engine error: ", err)
    			}


     //in JWT token IF DataAttribute=="Restricted" OR  "ExportAuthorizationRequirements" call the
     //following Esanctions Rule
    decisions, err := enforcer.Evaluate(map[string]interface{}{
                                            "UserNationality": "us",
                                            "UserLocation": "rr",
                                            "ResourceLocaleID": "us",
                                             	})


    			if err != nil {
    				log.Fatalf("Error Evaluating: ", err)
    			}

    declen := len(decisions)
    message := ""
     if declen == 0{
             message = "Policy Decision: Access Denied"
         }else{
              message = "Policy Decision: Access Allowed"
      }
      print(message)

}```

**Comment by jinmmin** [comment]
Hey, I can't reproduce the issue in linux or mac. 
Please change the import to `github.com/google/cel-policy-templates-go/policy` and check if your Go version is >= 1.13.
If it still does not work, try `go get github.com/google/cel-policy-templates-go`.
If it still does not work, try cloning the repo locally and use the local dependency in your mod file.

BTW, there are examples [here](https://github.com/google/cel-policy-templates-go/blob/master/policy/engine_test.go) for how to use the library.

**Comment by deshruch** [comment]
So do you mean you were able to run my code in the latest cel-policy-templates-go version?
Btw, I'm running this on Windows.
So far I have been cloning the repo and using it locally by adding it to C:\Program Files\Go\src and $USERHOME/go/src

What I see is the way the Engine is created has changed:

t.Run(tst.name, func(tt *testing.T) {
			opts := []EngineOption{
				StandardExprEnv(env),
				Selectors(labelSelector),
				RangeLimit(1),
				RuntimeTemplateOptions(
					runtime.Functions(test.Funcs...),
					runtime.NewCollectAggregator("policy.violation"),
					runtime.NewCollectAggregator("policy.report"),
					runtime.NewOrAggregator("policy.deny"),
				),
			}
			
			and so the code I wrote does not work with the latest cel-policy-templates-go.

**Comment by jinmmin** [comment]
I didn't have the `no matching versions for query "latest"` errors. But I could not run the code because of the interface change.

Sorry for the breakage. The repo is under development so we don't have a published release yet.
Are you planning to use it for production?

**Comment by deshruch** [comment]
Well we are deliberating on candidates. But if the code is not backward compatible, it does not seem like we could put it to production. We should not require to refactor code with every new version. Also, there is only master branch, so we cannot even refer to any branch/tags.

**Comment by jinmmin** [comment]
Have you talked to @TristonianJones about your use case? It was likely that we were not aware of the dependency, so there was no consideration for maintaining backwards compatibility earlier.
The updated interface is being used in a production system within google. I believe it will not change drastically going forward.
We can ask Tristan to create a tagged stable version if it helps.

**Comment by TristonianJones** [comment]
I can put together a release, but I hadn't yet as I was unaware that anyone was using the library publicly. The `SourceFile` was  sort of a hack that I'd put together, but there's a way to map to the new APIs if I spend a bit of time looking at it. I'll get back to you tomorrow with more details.

**Comment by TristonianJones** [comment]
Sorry for the delayed response @deshruch, but here's how to do what you were doing before:

```go
func main() {
	env, err := cel.NewEnv(stdDecls)
	if err != nil {
		log.Fatalf("cel.NewEnv(stdDecls) failed: %v", err)
	}
	engine, err := policy.NewEngine(policy.StandardExprEnv(env))
	if err != nil {
		log.Fatalf("policy.NewEngine() failed: %v", err)
	}
	tmpl, iss := engine.CompileTemplate("template-economic-sanctions.yaml")
	if iss.Err() != nil {
                log.Fatalf("engine.CompileTemplate() failed: %v", iss.Err())
	}
	err = engine.SetTemplate(tmpl.Metadata.Name, tmpl)
	if err != nil {
		log.Fatalf("engine.SetTemplate(%v) failed: %v", tmpl.Metadata.Name, err)
	}
	inst, iss := engine.CompileInstance("instance-economic-sanctions.yaml")
        if iss.Err() != nil {
                log.Fatalf("engine.CompileTemplate() failed: %v", iss.Err())
        }
	engine.AddInstance(inst)
        decisions, err = engine.EvalAll(map[string]interface{}{
		"UserNationality": "us",
		"UserLocation": "rr",
		"ResourceLocaleID": "us",
	})
       	if err != nil {
		log.Fatalf("Error Evaluating: ", err)
	}
	declen := len(decisions)
     	if declen == 0{
		print("Policy Decision: Access Denied")
	} else {
		print("Policy Decision: Access Allowed")
	}
}

func read(fileName string) *model.Source {
	tmplBytes, err := ioutil.ReadFile(fileName)
	if err != nil {
		log.Fatalf("ioutil.ReadFile(%v) failed: %v", fileName, err)
	}
	return model.ByteSource(tmplBytes, fileName)
}
```

Note, that the `evaluator` and `template` yaml files are now combined into a single `template` file. The use of the `SourceFile` option was removed in favor of more deliberate concurrency safe methods to `Compile`, `Set/Add`, and `Remove` templates and instances. There's also the notion of an `Environment` which you can use to declare your `stdDecls` into a yaml file as well. 

Feel free to ping if you have any questions.
